version: '3'

services:
  # frontend:
  #   image: eeacms/marine-frontend
  #   ports:
  #   - "${FRONTEND:-4000}:4000"
  #   depends_on:
  #   - backend
  #   environment:
  #     PORT: "${FRONTEND:-4000}"
  #     API_PATH: "http://localhost:${BACKEND:-8080}/Plone"
  #     INTERNAL_API_PATH: "http://backend:${BACKEND:-8080}/Plone"
  #     RAZZLE_API_PATH: "http://localhost:${BACKEND:-8080}/Plone"
  #     RAZZLE_INTERNAL_API_PATH: "http://backend:${BACKEND:-8080}/Plone"

  backend:
    image: eeacms/marine-backend
    ports:
      - '${BACKEND_PORT:-8080}:8080'
    environment:
      CORS_ALLOW_ORIGIN: 'http://localhost:${FRONTEND_PORT:-3000}'
    depends_on:
      - memcached
    volumes:
      - ./data:/data
      - ./backend/site.cfg:/plone/instance/site.cfg
      - ./backend/src:/plone/instance/src
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: memcached
    command:
      - '-m'
      - '512'
